project_identifier: kowak
api_key: 2bc319a7164349031f4f38d311e49daf
preserve_hierarchy: true
base_path: "/translations"
files:
  - source: "/**/props-en.json"
    translation: "/**/props-%two_letters_code%.json"