# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.define "kowak.dev"
  config.vm.provider :virtualbox do |v|
    v.name = "kowak.dev"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision :ansible do |ansible|
    ansible.tags = "noop"
    ansible.playbook = "main.yml"
  end
end
