---
- name: Update the list of available system packages
  shell: apt-get update

- name: Install newer version of system packages
  shell: apt-get upgrade -y 

- name: Creating apt sources list for node
  shell: wget -q -O - https://deb.nodesource.com/setup_8.x | sudo -E bash -

- name: Install packages needed by the application
  apt: pkg={{ item }} state=present
  with_items:
    - nodejs
    - git

- name: Install "pm2" node.js package globally.
  npm:
    name: pm2
    global: yes